### ISSUE TITLE
Uncaught TypeError: Cannot read property 'complete' of undefined 

### ISSUE THREAD

**Issue by seyhunak** [k9ordon/ghostrayder#1]
Hi,

@k9ordon. I'm getting "Uncaught TypeError: Cannot read property 'complete' of undefined" error at line.

<pre>app.src.coffee:442
if (@$headerImg.get(0).complete)
</pre>

Looks like Coffeescript cannot compile that file. How to get around this?

Environment:
Node.js: v0.10.20
NPM: 1.3.11
Ghost 0.3

**Comment by tobkow** [comment]
This assumes you have a blog cover image uploaded in Ghost's admin section. As a temporary walkaround you can just upload any blog cover image and this will disappear.

**Comment by seyhunak** [comment]
@windyrainman This workaround solves issue for listing page, but issue still up for child pages.

**Comment by k9ordon** [comment]
Theme child pages pages are not ready yet. 
They will also show the blog cover untill the ["Feature / cover images"](http://github.com/TryGhost/Ghost/wiki/Planned-Features#themes) part is done in ghost.
